repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--select=D100,D102,D103"]
  
  - repo: https://github.com/mrabhishekmore/custom_hooks
    rev: e9d3cc4b701ba705a85ba7f63480efd04991050f
    hooks:
      - id: audit-setup
      - id: check-sonar-quality-gate
        verbose: true
