repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--select=D100,D102,D103"]
  
  - repo: https://github.com/mrabhishekmore/custom_hooks
    rev: 220f5a0a8818920dc23d3a7f3b5afac65984f1ed
    hooks:
      - id: audit-setup
      - id: aqd-review
      - id: check-sonar-quality-gate
        verbose: true
